export interface User {
  userName?: string;
  firstName?: string;
  lastName?: string;
  userType?: string;
  phonNumber1?: string;
  phonNumber2?: string;
  fiscalAddress?: string;
  socialFacebook?: string;
  socialInstagram?: string;
  socialTwitter?: string;
  socialYoutube?: string;
  birthday: string;
  city: string;
  email: string;
  first_name: string;
  company: string;
  fiscal_address: string;
  id: number;
  imageData: string | null;
  last_name: string;
  password: string;
  phone_number1: string;
  phone_number2: string;
  profession: string;
  sequence: any;
  social_facebook: string;
  social_instagram: string;
  social_twitter: string;
  social_youtube: string;
  state: string;
  user_type: string;
  username: string;
}
