import React from 'react';
import {Box} from "@mui/material";
import Head from "next/head";
import {Navbar, Sidebar, Footer} from "../ui/client";

interface ClientLayoutProps {
  title?: string;
  children: JSX.Element
}

export function ClientLayout({title = 'Vision inmobiliaria', children}: ClientLayoutProps) {
  return (
    <Box sx={{ flexFlow: 1, marginTop: 10 }}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Sidebar />

      <Box>
        {children}
      </Box>
      <Footer />
    </Box>
  )
}
